on:
    workflow_dispatch:
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: node setup...
              uses: actions/setup-node@v2
              with:
                node-version: '20'
                registry-url: 'https://registry.npmjs.org'
            - name: install dependencies...
              run: npm ci
            - name: building...
              run: npm run build
            - name: publishing...
              run: npm publish 
              env:
                NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            